// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt_PlatformyDoOrganizacjiWydarzen.Models;

namespace Projekt_PlatformyDoOrganizacjiWydarzen.Migrations.Verify
{
    [DbContext(typeof(VerifyContext))]
    [Migration("20190513192341_Reg")]
    partial class Reg
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projekt_PlatformyDoOrganizacjiWydarzen.Models.VerifyModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Registered");

                    b.Property<int>("event_id");

                    b.Property<int>("ticket_id");

                    b.HasKey("id");

                    b.ToTable("VerifyModel");
                });
#pragma warning restore 612, 618
        }
    }
}
