// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt_PlatformyDoOrganizacjiWydarzen.Models;

namespace Projekt_PlatformyDoOrganizacjiWydarzen.Migrations.Tickets
{
    [DbContext(typeof(TicketsContext))]
    [Migration("20190503210308_TicketsUpdateGT")]
    partial class TicketsUpdateGT
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projekt_PlatformyDoOrganizacjiWydarzen.Models.TicketsModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NIP")
                        .HasMaxLength(10);

                    b.Property<int>("event_id");

                    b.Property<string>("event_type");

                    b.Property<string>("hour");

                    b.Property<string>("name");

                    b.Property<string>("place");

                    b.Property<int>("tickets_per_person");

                    b.Property<string>("user_mail");

                    b.Property<string>("user_name")
                        .IsRequired();

                    b.Property<string>("user_surname")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("TicketsModel");
                });
#pragma warning restore 612, 618
        }
    }
}
